services:
  - type: web
    name: skypiea-gateway
    runtime: image
    image:
      url: ghcr.io/itsreiji/litellm:latest
    envVars:
      - key: PORT
        value: 4000
    numInstances: 1
    healthCheckPath: /health/liveliness
    autoDeploy: true
